# Generated by Django 4.2.5 on 2023-09-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_alter_contact_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Your Default Value Here', max_length=255),
        ),
    ]
